-- Optional helper tables for the NATA địa danh portal. Run only if these tables are not already present.
create table if not exists public.place_articles (
  id bigint generated by default as identity primary key,
  place_slug text unique not null,
  place_name text,
  title text,
  content text,
  status text default 'draft',
  updated_at timestamptz default now()
);

create table if not exists public.community_submissions (
  id bigint generated by default as identity primary key,
  full_name text,
  contact text,
  place_name text,
  content text not null,
  status text default 'pending',
  created_at timestamptz default now()
);
